name: TEST

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: Run
      id: test
      run: |
        touch hoge.text
        echo "hoge1=ttt" >> $GITHUB_OUTPUT

    - name: test1
      if: ${{ success() && steps.test.outputs.hoge != '' }}
      run: 
        echo "test1 ${{ steps.test.outputs.hoge }}"

    - name: test2
      if: ${{ success() && steps.test.outputs.hoge1 == '' }}
      run: 
        echo "test2 ${{ steps.test.outputs.hoge1 }}"

    - name: test3
      if: ${{ success() && steps.test.outputs.hoge1 != '' }}
      run: 
        echo "test3 ${{ steps.test.outputs.hoge1 }}"
